Repository dsi-icl/optimise-core, pull requests merged in 2018-07, with the labels that each got.

#51 [WIP] Develop fixing promise to Develop - Phase 2
  optimise.postman_collection.json
  src/controllers/patientController.js
  src/controllers/treatmentController.js
  src/core/treatment.js
  src/routes/treatmentRoute.js
Labels: enhancement

#53 Merging stable version of the API.
  optimise.postman_collection.json
  src/controllers/demographicDataController.js
  src/controllers/treatmentController.js
  src/core/demographic.js
  src/routes/demographicRoute.js
Labels: enhancement

#55 Addressing issues where database creation is not tied to testing
  db/exampleDataForTesting/seed/loadExampleData.js
  installDB.js
  package-lock.json
  package.json
  src/utils/db-connection.js
  src/utils/db-handler.js
  test/ceController.test.js
  test/demographicController.test.js
  test/patientController.test.js
  test/setup.js
  test/teardown.js
  test/testControler.test.js
  test/treatmentController.test.js
  test/visitController.test.js
Labels: critical

#83 Adding medra code
  optimise.postman_collection.json
  package-lock.json
  src/controllers/dataController.js
  src/controllers/meddraController.js
  src/controllers/userController.js
  src/core/user.js
  src/optimiseServer.js
Labels: critical

#128 Added queries for a few search fields
  src/controllers/patientController.js
  src/core/patient.js
  src/utils/message-utils.js
  test/patientController.test.js
Labels: bug, critical
